module FileSystemApp
{
typedef sequence<octet> byteSeq;
  interface FileSystem
  {
      string readFile(in string title);
      void shutdown ();
      String getRecord (int num);
      boolean findFile (String title);
      void setServers ();
      boolean hasFile (String title);
      String otherServerSendsFile (String title) throws IOException;
      boolean otherServerHasFile() throws InvalidName, NotFound, CannotProceed, org.omg.CosNaming.NamingContextPackage.InvalidName;
      void writeFile(String title) throws IOException;
      void closeFile(String title);
  };
};
