module FileSystemApp
{
typedef sequence<octet> byteSeq;
  interface FileSystem
  {
      oneway void shutdown ();
      string getRecord (in long num);
      boolean findFile (in string title);
      oneway void setServers ();
      boolean hasFile (in string title);
      string otherServerSendsFile (in string title);
      boolean otherServerHasFile();
      oneway void writeFile(in string title);
      oneway void closeFile(in string title);
      oneway void deleteFile (in string title);
      oneway void saveFile(in string data, in long record, in string title); 
  };
};
