package FileSystemApp;


/**
* FileSystemApp/FileSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Wednesday, December 14, 2016 3:11:18 PM EST
*/

public interface FileSystemOperations
{
  void shutdown ();
  String getRecord (int num);
  boolean findFile (String title);
  void setServers ();
  boolean hasFile (String title);
  String otherServerSendsFile (String title);
  boolean otherServerHasFile ();
  void writeFile (String title);
  void closeFile (String title);
  void deleteFile (String title);
  void saveRecordToFile(String record, int recordNum, String title);
} // interface FileSystemOperations
