package FileSystemApp;


/**
* FileSystemApp/FileSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Monday, December 12, 2016 2:05:42 PM EST
*/

public interface FileSystemOperations 
{
  String sayHello ();
  String readFile (String title);
  void shutdown ();
  String readLocal (String title);
} // interface FileSystemOperations
