package FileSystemApp;


/**
* FileSystemApp/FileSystemPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Wednesday, December 14, 2016 3:11:18 PM EST
*/

public abstract class FileSystemPOA extends org.omg.PortableServer.Servant
 implements FileSystemApp.FileSystemOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("shutdown", new java.lang.Integer (0));
    _methods.put ("getRecord", new java.lang.Integer (1));
    _methods.put ("findFile", new java.lang.Integer (2));
    _methods.put ("setServers", new java.lang.Integer (3));
    _methods.put ("hasFile", new java.lang.Integer (4));
    _methods.put ("otherServerSendsFile", new java.lang.Integer (5));
    _methods.put ("otherServerHasFile", new java.lang.Integer (6));
    _methods.put ("writeFile", new java.lang.Integer (7));
    _methods.put ("closeFile", new java.lang.Integer (8));
    _methods.put ("deleteFile", new java.lang.Integer (9));
    _methods.put ("saveFile", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FileSystemApp/FileSystem/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       case 1:  // FileSystemApp/FileSystem/getRecord
       {
         int num = in.read_long ();
         String $result = null;
         $result = this.getRecord (num);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // FileSystemApp/FileSystem/findFile
       {
         String title = in.read_string ();
         boolean $result = false;
         $result = this.findFile (title);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // FileSystemApp/FileSystem/setServers
       {
         this.setServers ();
         out = $rh.createReply();
         break;
       }

       case 4:  // FileSystemApp/FileSystem/hasFile
       {
         String title = in.read_string ();
         boolean $result = false;
         $result = this.hasFile (title);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // FileSystemApp/FileSystem/otherServerSendsFile
       {
         String title = in.read_string ();
         String $result = null;
         $result = this.otherServerSendsFile (title);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // FileSystemApp/FileSystem/otherServerHasFile
       {
         boolean $result = false;
         $result = this.otherServerHasFile ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // FileSystemApp/FileSystem/writeFile
       {
         String title = in.read_string ();
         this.writeFile (title);
         out = $rh.createReply();
         break;
       }

       case 8:  // FileSystemApp/FileSystem/closeFile
       {
         String title = in.read_string ();
         this.closeFile (title);
         out = $rh.createReply();
         break;
       }

       case 9:  // FileSystemApp/FileSystem/deleteFile
       {
         String title = in.read_string ();
         this.deleteFile (title);
         out = $rh.createReply();
         break;
       }

       case 10:  // FileSystemApp/FileSystem/saveFile
       {
         String data = in.read_string ();
         int record = in.read_long ();
         String title = in.read_string ();
         this.saveFile (data, record, title);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FileSystemApp/FileSystem:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileSystem _this() 
  {
    return FileSystemHelper.narrow(
    super._this_object());
  }

  public FileSystem _this(org.omg.CORBA.ORB orb) 
  {
    return FileSystemHelper.narrow(
    super._this_object(orb));
  }


} // class FileSystemPOA
