package FileSystemApp;

import java.io.IOException;

import org.omg.CORBA.ORBPackage.InvalidName;
import org.omg.CosNaming.NamingContextPackage.CannotProceed;
import org.omg.CosNaming.NamingContextPackage.NotFound;

/**
* FileSystemApp/FileSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Wednesday, December 14, 2016 11:55:46 AM EST
*/

public interface FileSystemOperations
{
//  String readFile (String title);
  void shutdown ();
  String getRecord (int num);
  boolean findFile (String title);
  void setServers ();
  boolean hasFile (String title);
  String otherServerSendsFile (String title) throws IOException;
  boolean otherServerHasFile()	throws InvalidName, NotFound, CannotProceed, org.omg.CosNaming.NamingContextPackage.InvalidName;
  void writeFile(String title) throws IOException;
} // interface FileSystemOperations
