package FileSystemApp;

/**
 * FileSystemApp/FileSystemPOA.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from FileSystem.idl Thursday, November 10, 2016
 * 2:45:54 PM EST
 */

public abstract class FileSystemPOA extends org.omg.PortableServer.Servant
		implements FileSystemApp.FileSystemOperations, org.omg.CORBA.portable.InvokeHandler
{

	// Constructors

	private static java.util.Hashtable<String, Integer> _methods = new java.util.Hashtable<String, Integer>();
	static
	{
		_methods.put("sayHello", new java.lang.Integer(0));
		_methods.put("shutdown", new java.lang.Integer(1));
		_methods.put("readFile", new java.lang.Integer(2));
	}

	/**
	 * @see org.omg.CORBA.portable.InvokeHandler#_invoke(java.lang.String, org.omg.CORBA.portable.InputStream, org.omg.CORBA.portable.ResponseHandler)
	 */
	public org.omg.CORBA.portable.OutputStream _invoke(String $method, org.omg.CORBA.portable.InputStream in,
			org.omg.CORBA.portable.ResponseHandler $rh)
	{
		org.omg.CORBA.portable.OutputStream out = null;
		java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
		if (__method == null)
			throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

		switch (__method.intValue())
		{
		case 0: // FileSystemApp/FileSystem/shutdown
		{
			this.shutdown();
			out = $rh.createReply();
			break;
		}

		case 1: // FileSystemApp/FileSystem/findFile
		{
			String $title = in.read_string();
			boolean $result = false;
			$result = this.findFile($title);
			out = $rh.createReply();
			out.write_boolean($result);
			break;
		}

		case 2: //FileSystemApp/FileSystem/hasFile
		{
			String $title = in.read_string();
			boolean $result = false;
			$result = this.hasFile($title);
			out = $rh.createReply();
			out.write_boolean($result);
			break;
		}

		case 3: //FileSystemApp/FileSystem/getRecord
		{
			int $record = in.read_long();
			String $result = "";
			$result = this.getRecord($record);
			out = $rh.createReply();
			out.write_string($result);
			break;
		}

		case 4: //FileSystemApp/FileSystem/otherServerHasFile
		{
			boolean $result = false;
			$result = this.otherServerHasFile();
			out = $rh.createReply();
			out.write_boolean($result);
			break;
		}

		case 5: //FileSystemApp/FileSystem/otherServerSendsFile
		{
			String $title = in.read_string();
			String $result = "";
			$result = this.otherServerSendsFile($title);
			out = $rh.createReply();
			out.write_string($result);
		}

		case 6: //FileSystemApp/FileSystem/writeFile
		{
			String $title = in.read_string();
			this.writeFile($title);
			out = $rh.createReply();
		}

		case 7: //FileSystemApp/FileSystem/closeFile
		{
			String $title = in.read_string();
			this.closeFile($title);
			out = $rh.createReply();
		}

		case 8: //FileSystemApp/FileSystem/deleteFile
		{
			String $title = in.read_string();
			this.deleteFile($title);
			out = $rh.createReply();
		}

		case 9: //FileSystemApp/FileSystem/saveRecordToFile
		{
			String $record = in.read_string();
			int $recordNum = in.read_long();
			String $title = in.read_string();

			this.saveRecordToFile($record, $recordNum, $title);
			out = $rh.createReply();
		}

		default:
			throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
		}

		return out;
	} // _invoke

	// Type-specific CORBA::Object operations
	private static String[] __ids =
	{ "IDL:FileSystemApp/FileSystem:1.0" };

	/**
	 * @see org.omg.PortableServer.Servant#_all_interfaces(org.omg.PortableServer.POA, byte[])
	 */
	public String[] _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId)
	{
		return (String[]) __ids.clone();
	}

	/**
	 * @return the FileSystem we are working with
	 */
	public FileSystem _this()
	{
		return FileSystemHelper.narrow(super._this_object());
	}

	/**
	 * @param orb our Corba object
	 * @return the FileSystem it contains
	 */
	public FileSystem _this(org.omg.CORBA.ORB orb)
	{
		return FileSystemHelper.narrow(super._this_object(orb));
	}

}
